/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class verifikasi extends javax.swing.JFrame {

    int tmp;
    int ambil;
    /**
     * Creates new form verifikasi
     */
    public verifikasi(int e, String k, String b, String n, String t, int u) {
        initComponents();
        this.tmp = e;
        this.ambil = u;
        if(k.equals("000")){
            kode.setText("009");
        } else {
            kode.setText(k);
        }
        rekening.setText(n);
        transfer.setText("Rp "+t);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        transfer = new javax.swing.JLabel();
        kode = new javax.swing.JLabel();
        rekening = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        jButton4.setBackground(new java.awt.Color(255, 102, 102));
        jButton4.setText("CANCEL");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(50, 210, 130, 40);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("VERIFICATION");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(160, 10, 200, 40);

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("REG NO");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 120, 110, 30);

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("AMOUNT");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 160, 140, 30);

        jLabel10.setFont(new java.awt.Font("Cambria", 0, 17)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("BANK CODE");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(70, 80, 120, 30);

        transfer.setFont(new java.awt.Font("Cambria", 0, 17)); // NOI18N
        transfer.setForeground(new java.awt.Color(255, 255, 255));
        transfer.setText("= .");
        jPanel1.add(transfer);
        transfer.setBounds(220, 160, 110, 30);

        kode.setFont(new java.awt.Font("Cambria", 0, 17)); // NOI18N
        kode.setForeground(new java.awt.Color(255, 255, 255));
        kode.setText("= .");
        jPanel1.add(kode);
        kode.setBounds(220, 80, 110, 30);

        rekening.setFont(new java.awt.Font("Cambria", 0, 17)); // NOI18N
        rekening.setForeground(new java.awt.Color(255, 255, 255));
        rekening.setText("= .");
        jPanel1.add(rekening);
        rekening.setBounds(220, 120, 110, 30);

        jButton5.setBackground(new java.awt.Color(51, 255, 102));
        jButton5.setText("CONTINUE");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(280, 210, 130, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 500, 290);

        setSize(new java.awt.Dimension(516, 332));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new ChooseTransfer(tmp).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        tmp -= ambil;
        new Success(tmp).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(verifikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(verifikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(verifikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(verifikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kode;
    private javax.swing.JLabel rekening;
    private javax.swing.JLabel transfer;
    // End of variables declaration//GEN-END:variables
}
